version: '3.8'

services:

  todo-app:
    build: .
    image: todo-app:1.0
    container_name: todo-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - FRONTEND_URL=${FRONTEND_URL}

  mysql-db:
    image: mysql:latest
    container_name: mysql-db-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db_dev
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
